export const NORMAL_CONSUMABLE_BASE_DROP_RATE = 0.5
export const SPELL_TRACE_BASE_DROP_RATE = 1
export const SOL_ERDA_FRAGMENT_BASE_DROP_RATE = 0.0425
export const CORE_GEMSTONE_BASE_DROP_RATE = 0.028
export const SYMBOL_BASE_DROP_RATE = 0.0015
